# These are supported funding model platforms

github: [rainxchzed]
buy_me_a_coffee: rainxchzed
custom: https://golden-kodee.awardsplatform.com/entry/vote/mNKjQxkX/vnZAamgg?search=8154c88ed0eccba9-70
